name: flake8

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flake8:
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.11, 3.12]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Remove Zone.Identifier streams
      run: |
        Get-ChildItem -Recurse -Stream Zone.Identifier -ErrorAction SilentlyContinue | 
        ForEach-Object { Remove-Item $_.FileName -Stream Zone.Identifier }
      shell: pwsh


    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
      shell: cmd

    - name: Lint with flake8
      run: |
        flake8 .
      shell: cmd

